### ISSUE TITLE
Available Datasets

### ISSUE THREAD

**Issue by awaab** [vitkl/orthologsBioMART#5]
Where can I get a list of the available datasets (for different species) such as "mmusculus_gene_ensembl"?

**Comment by vitkl** [comment]
Please check the documentation for `pybiomart`. It should be similar to:

```python
# find correct dataset name for your species
from pybiomart import Server
server = Server(host='http://www.ensembl.org')
server.marts['ENSEMBL_MART_ENSEMBL'].list_datasets()
```

**Comment by awaab** [comment]
> Please check the documentation for `pybiomart`. It should be similar to:
> 
> ```python
> # find correct dataset name for your species
> from pybiomart import Server
> server = Server(host='http://www.ensembl.org')
> server.marts['ENSEMBL_MART_ENSEMBL'].list_datasets()
> ```

Thank you.
